version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
